FROM nginx

# To set configuration for nginx. To take our configuration file and copy it into the image, termorary container. and all these file are in the filesystem
# To overwrite the default.conf file that exists inside the nginx image.
COPY ./default.conf /etc/nginx/conf.d/default.conf
